export enum OrganizationType {
    SCHOOL = 'SCHOOL',
    COLLEGE = 'COLLEGE',
    UNIVERSITY = 'UNIVERSITY',
    INSTITUTION = 'INSTITUTION',
    GROUP = 'GROUP',
    TRAINING_CENTER = 'TRAINING_CENTER',
    COACHING_CENTER = 'COACHING_CENTER'
}
