import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { HasPermissionDirective } from '../../../../shared/directives/has-permission.directive';
import { AppToastComponent } from '../../../../core/feedback/app-toast.component';
import { UiFeedbackService } from '../../../../core/feedback/ui-feedback.service';
import { extractApiError } from '../../../../shared/utils/api-error.util';
import { SaasPageHeaderComponent } from '../../../../shared/ui/saas';
import { finalizeBusy, TcPageSkeletonComponent } from '../../../../shared/ui/loading';
import { FeesApiService } from '../../services/fees-api.service';
import { FEES_RESOURCES, FinanceSettings, PaymentMethod } from '../../models/fees.model';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../../../environments/environment';
import { map } from 'rxjs';
import { PayrollApiService } from '../../../payroll/services/payroll-api.service';
import {
  PAYROLL_RESOURCES,
  PayrollSettings,
  WorkingDaysBasis,
  LopHandling,
  SalaryRounding
} from '../../../payroll/models/payroll.model';
import { ExpensesApiService } from '../../../expenses/services/expenses-api.service';
import { EXPENSE_RESOURCES, ExpenseSettings } from '../../../expenses/models/expenses.model';

type SettingsTab = 'fees' | 'payroll' | 'expenses';

@Component({
  selector: 'app-fees-settings-page',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, HasPermissionDirective, AppToastComponent, SaasPageHeaderComponent, TcPageSkeletonComponent],
  templateUrl: './fees-settings-page.component.html',
  styleUrls: ['./fees-settings-page.component.scss', '../../fees.shared.scss', '../../../payroll/payroll.shared.scss']
})
export class FeesSettingsPageComponent implements OnInit {
  private readonly api = inject(FeesApiService);
  private readonly payrollApi = inject(PayrollApiService);
  private readonly expensesApi = inject(ExpensesApiService);
  private readonly fb = inject(FormBuilder);
  private readonly feedback = inject(UiFeedbackService);
  private readonly http = inject(HttpClient);
  private readonly cdr = inject(ChangeDetectorRef);

  readonly resources = FEES_RESOURCES;
  readonly payrollResources = PAYROLL_RESOURCES;
  readonly expenseResources = EXPENSE_RESOURCES;
  activeTab: SettingsTab = 'fees';

  loading = true;
  saving = false;
  error: string | null = null;
  settings: FinanceSettings | null = null;
  methods: PaymentMethod[] = [];
  years: { id: number; name: string }[] = [];
  generateYearId: number | null = null;

  payrollLoading = false;
  payrollSaving = false;
  payrollError: string | null = null;
  payrollSettings: PayrollSettings | null = null;
  expensesLoading = false;
  expensesSaving = false;
  expensesError: string | null = null;
  expensesSettings: ExpenseSettings | null = null;
  expenseNumberPreview = '';

  generationForm = this.fb.group({
    autoGenerateDues: [true],
    generationLeadDays: [5, [Validators.required, Validators.min(0)]],
    defaultDueDayForNewStructures: [10, [Validators.required, Validators.min(1), Validators.max(28)]]
  });

  payrollForm = this.fb.group({
    frequency: [{ value: 'MONTHLY', disabled: true }],
    defaultGenerationDay: [1, [Validators.required, Validators.min(1), Validators.max(28)]],
    approvalRequired: [true],
    defaultPaymentMethodId: [null as number | null],
    pfEnabled: [false],
    esiEnabled: [false],
    professionalTaxEnabled: [false],
    tdsEnabled: [false],
    workingDaysBasis: ['WORKING_DAYS' as WorkingDaysBasis, Validators.required],
    includePaidLeave: [true],
    lopHandling: ['PRORATE_GROSS' as LopHandling, Validators.required],
    salaryRounding: ['NEAREST_RUPEE' as SalaryRounding, Validators.required],
    payslipNumberFormat: [''],
    payslipOrgName: [''],
    showOrgLogo: [true],
    showAuthorizedSignatory: [true]
  });

  expensesForm = this.fb.group({
    approvalRequired: [true],
    numberPrefix: ['EXP', Validators.required],
    numberYearFormat: ['YYYY', Validators.required],
    numberPadWidth: [4, [Validators.required, Validators.min(1), Validators.max(10)]],
    numberStart: [1, [Validators.required, Validators.min(1)]],
    numberSequencePerYear: [true],
    defaultPaymentMethodId: [null as number | null],
    maxAttachmentBytes: [10485760, [Validators.required, Validators.min(1)]],
    allowedAttachmentContentTypes: ['application/pdf,image/jpeg,image/png', Validators.required]
  });

  ngOnInit(): void {
    this.http.get<{ success: boolean; data: { id: number; name: string }[] }>(`${environment.baseUrl}/students/academic-years`)
      .pipe(map(r => r.data ?? []))
      .subscribe(years => {
        this.years = years;
        this.generateYearId = years[0]?.id ?? null;
      });
    this.load();
  }

  setTab(tab: SettingsTab): void {
    this.activeTab = tab;
    if (tab === 'payroll' && !this.payrollSettings && !this.payrollLoading) {
      this.loadPayroll();
    }
    if (tab === 'expenses' && !this.expensesSettings && !this.expensesLoading) {
      this.loadExpenses();
    }
  }

  refreshActiveTab(): void {
    if (this.activeTab === 'fees') {
      this.load();
    } else if (this.activeTab === 'payroll') {
      this.loadPayroll();
    } else {
      this.loadExpenses();
    }
  }

  loadExpenses(): void {
    this.expensesLoading = true;
    this.expensesError = null;
    this.expensesApi.getSettings().pipe(finalizeBusy(v => (this.expensesLoading = v))).subscribe({
      next: settings => {
        this.expensesSettings = settings;
        this.expensesForm.reset(settings);
        this.refreshExpensePreview();
      },
      error: err => {
        this.expensesError = extractApiError(err, 'Request failed').message || 'Expense settings are not provisioned yet.';
      }
    });
  }

  refreshExpensePreview(): void {
    this.expensesApi.numberPreview().subscribe({ next: value => this.expenseNumberPreview = value, error: () => {
      const raw = this.expensesForm.getRawValue();
      this.expenseNumberPreview = `${raw.numberPrefix || 'EXP'}-${new Date().getFullYear()}-${String(raw.numberStart || 1).padStart(Number(raw.numberPadWidth || 4), '0')}`;
    }});
  }

  saveExpenses(): void {
    if (this.expensesForm.invalid) { this.expensesForm.markAllAsTouched(); return; }
    this.expensesSaving = true;
    const raw = this.expensesForm.getRawValue();
    const body: ExpenseSettings = {
      approvalRequired: !!raw.approvalRequired,
      numberPrefix: raw.numberPrefix!.trim(),
      numberYearFormat: raw.numberYearFormat!.trim(),
      numberPadWidth: Number(raw.numberPadWidth),
      numberStart: Number(raw.numberStart),
      numberSequencePerYear: !!raw.numberSequencePerYear,
      defaultPaymentMethodId: raw.defaultPaymentMethodId ?? null,
      maxAttachmentBytes: Number(raw.maxAttachmentBytes),
      allowedAttachmentContentTypes: raw.allowedAttachmentContentTypes!.trim()
    };
    this.expensesApi.updateSettings(body).pipe(finalizeBusy(v => (this.expensesSaving = v))).subscribe({
      next: settings => { this.expensesSettings = settings; this.feedback.success('Expense settings saved', 'Configuration updated.'); this.refreshExpensePreview(); },
      error: err => { this.feedback.error('Save failed', extractApiError(err, 'Request failed').message); }
    });
  }

  load(): void {
    this.loading = true;
    this.error = null;
    this.api.getSettings().pipe(finalizeBusy(v => (this.loading = v))).subscribe({
      next: settings => {
        this.settings = settings;
        this.generationForm.reset({
          autoGenerateDues: settings.autoGenerateDues,
          generationLeadDays: settings.generationLeadDays,
          defaultDueDayForNewStructures: settings.defaultDueDayForNewStructures
        });
      },
      error: err => {
        this.error = extractApiError(err, 'Request failed').message || 'Settings are not provisioned yet. Contact an administrator.';
      }
    });
    this.api.listPaymentMethods().subscribe({
      next: methods => this.methods = methods,
      error: () => this.methods = []
    });
  }

  loadPayroll(): void {
    this.payrollLoading = true;
    this.payrollError = null;
    this.payrollApi.getSettings().pipe(finalizeBusy(v => {
      this.payrollLoading = v;
      this.cdr.detectChanges();
    })).subscribe({
      next: settings => {
        this.payrollSettings = settings;
        this.payrollForm.reset({
          frequency: 'MONTHLY',
          defaultGenerationDay: settings.defaultGenerationDay,
          approvalRequired: settings.approvalRequired,
          defaultPaymentMethodId: settings.defaultPaymentMethodId ?? null,
          pfEnabled: settings.pfEnabled,
          esiEnabled: settings.esiEnabled,
          professionalTaxEnabled: settings.professionalTaxEnabled,
          tdsEnabled: settings.tdsEnabled,
          workingDaysBasis: settings.workingDaysBasis,
          includePaidLeave: settings.includePaidLeave,
          lopHandling: settings.lopHandling,
          salaryRounding: settings.salaryRounding,
          payslipNumberFormat: settings.payslipNumberFormat ?? '',
          payslipOrgName: settings.payslipOrgName ?? '',
          showOrgLogo: settings.showOrgLogo,
          showAuthorizedSignatory: settings.showAuthorizedSignatory
        });
        this.cdr.detectChanges();
      },
      error: err => {
        this.payrollError = extractApiError(err, 'Request failed').message || 'Payroll settings are not provisioned yet.';
        this.cdr.detectChanges();
      }
    });
  }

  saveGeneration(): void {
    if (this.generationForm.invalid) {
      this.generationForm.markAllAsTouched();
      return;
    }
    this.saving = true;
    const raw = this.generationForm.getRawValue();
    this.api.updateGenerationSettings({
      autoGenerateDues: !!raw.autoGenerateDues,
      generationLeadDays: Number(raw.generationLeadDays ?? 0),
      defaultDueDayForNewStructures: Number(raw.defaultDueDayForNewStructures ?? 10)
    }).pipe(finalizeBusy(v => (this.saving = v))).subscribe({
      next: settings => {
        this.settings = settings;
        this.feedback.success('Settings saved', 'Fee generation settings updated.');
      },
      error: err => {
        this.feedback.error('Save failed', extractApiError(err, 'Request failed').message);
      }
    });
  }

  runGeneration(): void {
    if (this.generateYearId == null) return;
    this.saving = true;
    this.api.runGeneration(this.generateYearId).pipe(finalizeBusy(v => (this.saving = v))).subscribe({
      next: () => {
        this.feedback.success('Generation started', 'Dues generation completed for the selected year.');
      },
      error: err => {
        this.feedback.error('Generation failed', extractApiError(err, 'Request failed').message);
      }
    });
  }

  savePayroll(): void {
    if (this.payrollForm.invalid) {
      this.payrollForm.markAllAsTouched();
      return;
    }
    this.payrollSaving = true;
    const raw = this.payrollForm.getRawValue();
    const body: Partial<PayrollSettings> = {
      frequency: 'MONTHLY',
      defaultGenerationDay: Number(raw.defaultGenerationDay ?? 1),
      approvalRequired: !!raw.approvalRequired,
      defaultPaymentMethodId: raw.defaultPaymentMethodId ?? null,
      pfEnabled: !!raw.pfEnabled,
      esiEnabled: !!raw.esiEnabled,
      professionalTaxEnabled: !!raw.professionalTaxEnabled,
      tdsEnabled: !!raw.tdsEnabled,
      workingDaysBasis: raw.workingDaysBasis as WorkingDaysBasis,
      includePaidLeave: !!raw.includePaidLeave,
      lopHandling: raw.lopHandling as LopHandling,
      salaryRounding: raw.salaryRounding as SalaryRounding,
      payslipNumberFormat: (raw.payslipNumberFormat || '').trim() || null,
      payslipOrgName: (raw.payslipOrgName || '').trim() || null,
      showOrgLogo: !!raw.showOrgLogo,
      showAuthorizedSignatory: !!raw.showAuthorizedSignatory
    };
    this.payrollApi.updateSettings(body).pipe(finalizeBusy(v => (this.payrollSaving = v))).subscribe({
      next: settings => {
        this.payrollSettings = settings;
        this.feedback.success('Payroll settings saved', 'Configuration updated.');
      },
      error: err => {
        this.feedback.error('Save failed', extractApiError(err, 'Request failed').message);
      }
    });
  }
}
